language: python
sudo: required
python:
    - 3.5

services:
    - docker

before_install:
    - nvm install 9.9.0
    - nvm use 9.9.0
    - npm i -g yarn@0.16.1

install:
    - pip install --upgrade setuptools
    - pip install codecov
    - pip install -Ur requirements-dev.txt
    - python setup.py develop
    - yarn install
    - pip freeze

script:
    make ci
after_success:
    codecov

env:
    matrix:
        - PYTHONASYNCIODEBUG=x
        - PYTHONASYNCIODEBUG=
